# Site settings
title: sacah.net
email: sacah@sacah.net
description: > # this means to ignore newlines until "baseurl:"
  A dumping ground for things that interest me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sacah.net" # the base hostname & protocol for your site
twitter_username: sacahnet
github_username:  sacah
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
paginate: 10
picture:
  source: "img"
  output: "generated"
  markup: "picture"
  presets:
    default:
      attr:
        class: "post-img"
      source_default:
        width: "300"
      source_600:
        width: "600"
        media: "(min-width: 230px) and (max-width: 430px) and (min-device-pixel-ratio: 1.5)"
      source_500:
        width: "500"
        media: "(min-width: 430px) and (max-width: 830px)"
      source_1000:
        width: "1000"
        media: "(min-width: 430px) and (max-width: 830px) and (min-device-pixel-ratio: 1.5)"
      source_900:
        width: "900"
        media: "(min-width: 830px) and (max-width: 1200px)"
      source_1800:
        width: "900"
        media: "(min-width: 830px) and (max-width: 1200px) and (min-device-pixel-ratio: 1.5)"
      source_1280:
        width: "1280"
        media: "(min-width: 1200px) and (max-width: 1600px)"
      source_2560:
        width: "1280"
        media: "(min-width: 1200px) and (max-width: 1600px) and (min-device-pixel-ratio: 1.5)"
      source_1680:
        width: "1680"
        media: "(min-width: 1600px)"
      source_3360:
        width: "1680"
        media: "(min-width: 1600px) and (min-device-pixel-ratio: 1.5)"